# Copyright (c) 2017 ChromaWay Inc. See README for license information.
version: '3.1'

services:

  postgres:
    image: chromaway/postgres:2.4.3-beta
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postchain

  postchain:
    image: chromaway/postchain-jib:2.4.4-beta
    ports:
      - 7740:7740
    volumes:
      - ./config:/app/config
    environment:
      - POSTCHAIN_DB_URL=jdbc:postgresql://postgres/postchain
    depends_on:
      - postgres

volumes:
  pgdata:
  postchain_config:
