Configuration:
  name: Default
  monitorInterval: 30 # sec.

  Properties:
    Property:
    - name: logs
      value: "logs"
    - name: logfile
      value: "ci"
    - name: logpattern
      value: "%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} -%replace{%notEmpty{ [%notEmpty{bc-rid=%.-2X{blockchainRID}:%.4X{blockchainRID}}%notEmpty{, chain-id=%X{chainIID}}%notEmpty{, block-rid=%.-2X{blockRID}:%.4X{blockRID}}]:}}{\\[, }{[} %msg%n"

  Appenders:
    Console:
      - name: ConsoleAppender
        PatternLayout:
          pattern: ${logpattern}
      - name: SimpleConsoleAppender
        PatternLayout:
          pattern: "+++ %msg +++%n"
    RollingFile:
      - name: FileAppender
        fileName: "${logs}/${logfile}.log"
        filePattern: "${logs}/${logfile}.%d{yyyy-MM-dd-hh-mm-ss}.log"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 MB
        DefaultRollOverStrategy:
          max: 10
        PatternLayout:
          pattern: ${logpattern}
      - name: SimpleFileAppender
        fileName: "${logs}/${logfile}.log"
        filePattern: "${logs}/${logfile}.%d{yyyy-MM-dd-hh-mm-ss}.log"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 MB
        DefaultRollOverStrategy:
          max: 10
        PatternLayout:
          pattern: "+++ %msg +++%n"


  Loggers:

    Root:
      level: warn
      AppenderRef:
      - ref: ConsoleAppender
      - ref: FileAppender

    Logger:

      - name: org.testcontainers
        level: info
        additivity: false
        AppenderRef:
        - ref: ConsoleAppender
          level: warn
        - ref: FileAppender

      - name: net.postchain
        level: debug
        additivity: false
        AppenderRef:
        - ref: ConsoleAppender
          level: warn
        - ref: FileAppender

      - name: net.postchain.devtools.IntegrationTestSetup
        level: debug
        additivity: false
        AppenderRef:
          - ref: SimpleConsoleAppender
          - ref: SimpleFileAppender

      - name: net.postchain.devtools.ConfigFileBasedIntegrationTest
        level: debug
        additivity: false
        AppenderRef:
          - ref: SimpleConsoleAppender
          - ref: SimpleFileAppender
