Configuration:
  name: Default
  monitorInterval: 30 # sec.

  Properties:
    Property:
    - name: logs
      value: "logs"
    - name: logfile
      value: "ci.log"
    - name: logpattern
      value: "%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

  Appenders:
    Console:
      - name: ConsoleAppender
        target: SYSTEM_OUT
        PatternLayout:
          pattern: ${logpattern}
      - name: SimpleConsoleAppender
        target: SYSTEM_OUT
        PatternLayout:
          pattern: "+++ %msg +++%n"
    RollingFile:
      - name: FileAppender
        fileName: "${logs}/${logfile}"
        filePattern: "${logs}/${logfile}.%d{yyyy-MM-dd-hh-mm}.log"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 MB
        DefaultRollOverStrategy:
          max: 10
        PatternLayout:
          pattern: ${logpattern}
      - name: SimpleFileAppender
        fileName: "${logs}/${logfile}"
        filePattern: "${logs}/${logfile}.%d{yyyy-MM-dd-hh-mm}.log"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 MB
        DefaultRollOverStrategy:
          max: 10
        PatternLayout:
          pattern: "+++ %msg +++%n"


  Loggers:

    Root:
      level: warn
      AppenderRef:
      - ref: ConsoleAppender
      - ref: FileAppender

    Logger:

      - name: net.postchain
        level: debug
        additivity: false
        AppenderRef:
        - ref: ConsoleAppender
          level: warn
        - ref: FileAppender

      - name: net.postchain.devtools.IntegrationTestSetup
        level: debug
        additivity: false
        AppenderRef:
          - ref: SimpleConsoleAppender
          - ref : SimpleFileAppender
