image: maven:3.8.4-openjdk-11

pipelines:
  default:
    - step:
        size: 2x
        max-time: 60
        caches:
          - maven
        script:
          - export POSTCHAIN_TEST_MASTER_HOST=172.17.0.1
          - export TESTCONTAINERS_RYUK_DISABLED=true
#          - mvn -e -B -P ci clean verify -DskipSurefireTests=true
          - mvn -e -B -P ci clean install
        services:
          - postgres
          - docker

definitions:
  services:
    docker:
      memory: 4096
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'postchain'
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'
