image: maven:3.6-jdk-8-alpine
pipelines:
  default:
    - step:
        max-time: 60
        script:
          - mvn -B -P ci clean install
        services: 
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'postchain' 
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'