image: maven:3.6-jdk-8-alpine

pipelines:
  default:
    - step:
        max-time: 60
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - export DOCKER_HOST=tcp://127.0.0.1:2376
          - docker version
#          - docker-compose version
          - mvn -X -B -P ci clean install
        services:
          - postgres
          - docker

definitions:
  services:
#    docker:
#      memory: 3072
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'postchain'
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'
