image: maven:3.6-jdk-8-alpine
pipelines:
  default:
    - step:
        max-time: 60
        caches:
          - maven
        script:
          - mvn --settings settings.xml clean deploy -DskipTests -Diam-user-access-key-id=AKIA5Z4BLV23UVYKWTVB -Diam-user-secret-key=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

        services: 
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'postchain' 
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'