image: maven:3.6-jdk-8-alpine

pipelines:
  default:
    - step:
        max-time: 60
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - printenv MAVEN_OPTS
          #          - export MAVEN_OPTS="-Xms1024m -Xmx2048m"
          - mvn -e -B -P ci clean install
        services:
          - postgres
          - docker

definitions:
  services:
    docker:
      memory: 2048
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'postchain'
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'
