image: maven:3.5-ibmjava-8
pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B -P ci clean install -X
        services: 
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'postchain' 
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'