image: maven:3.5-jdk-8
pipelines:
  default:
    - step:
        script:
          - mvn -P clean install
        services: 
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'postchain' 
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'