image: maven:3.6-jdk-8-alpine

pipelines:
  default:
    - step:
        size: 2x
        max-time: 60
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - mvn -e -B -P ci clean install
	      - cd ./postchain-devtools
	      - mvn verify -Pfailsafe -Dskip.surefire.tests
        services:
          - postgres
          - docker

definitions:
  services:
    docker:
      memory: 4096
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'postchain'
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'
