# Copyright (c) 2017 ChromaWay Inc. See README for license information.
version: '3.1'

services:

  postgres:
    image: chromaway/postgres:2.4.3-beta
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postchain

  postchain:
    image: chromaway/postchain:2.4.3-beta
    ports:
      - 7740:7740
    volumes:
      - ./postchain_config:/postchain-node/external_config
    environment:
      - ENV_NODE_CONFIG=./external_config/config.0.properties
      - ENV_BLOCKCHAIN_CONFIG=./external_config/blockchain_config.xml
      - ENV_BLOCKCHAIN_RID=78967baa4768cbcef11c508326ffb13a956689fcb6dc3ba17f4b895cbb1577a3
      - ENV_CHAIN_ID=1
    depends_on:
      - postgres

volumes:
  pgdata:
  postchain_config:
