/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MerkleProofInterface extends ethers.utils.Interface {
  functions: {
    "c_0xd05a8f13(bytes32)": FunctionFragment;
    "root(bytes32[])": FunctionFragment;
    "verify(bytes32[],bytes32,uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xd05a8f13",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "root", values: [BytesLike[]]): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike[], BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xd05a8f13",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "root", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class MerkleProof extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MerkleProofInterface;

  functions: {
    c_0xd05a8f13(
      c__0xd05a8f13: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    root(nodes: BytesLike[], overrides?: CallOverrides): Promise<[string]>;

    verify(
      proofs: BytesLike[],
      leaf: BytesLike,
      position: BigNumberish,
      rootHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  c_0xd05a8f13(
    c__0xd05a8f13: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  root(nodes: BytesLike[], overrides?: CallOverrides): Promise<string>;

  verify(
    proofs: BytesLike[],
    leaf: BytesLike,
    position: BigNumberish,
    rootHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    c_0xd05a8f13(
      c__0xd05a8f13: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    root(nodes: BytesLike[], overrides?: CallOverrides): Promise<string>;

    verify(
      proofs: BytesLike[],
      leaf: BytesLike,
      position: BigNumberish,
      rootHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    c_0xd05a8f13(
      c__0xd05a8f13: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    root(nodes: BytesLike[], overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      proofs: BytesLike[],
      leaf: BytesLike,
      position: BigNumberish,
      rootHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xd05a8f13(
      c__0xd05a8f13: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    root(
      nodes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      proofs: BytesLike[],
      leaf: BytesLike,
      position: BigNumberish,
      rootHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
