/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PostchainInterface extends ethers.utils.Interface {
  functions: {
    "c_0x94e56d13(bytes32)": FunctionFragment;
    "isValidNodes(bytes32,address[])": FunctionFragment;
    "isValidSignatures(bytes32,bytes[],address[])": FunctionFragment;
    "verifyBlock(bytes32,bytes,bytes[],bytes32[],uint256,address[])": FunctionFragment;
    "verifyEvent(bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0x94e56d13",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidNodes",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignatures",
    values: [BytesLike, BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBlock",
    values: [
      BytesLike,
      BytesLike,
      BytesLike[],
      BytesLike[],
      BigNumberish,
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvent",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0x94e56d13",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvent",
    data: BytesLike
  ): Result;

  events: {};
}

export class Postchain extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PostchainInterface;

  functions: {
    c_0x94e56d13(
      c__0x94e56d13: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    isValidNodes(
      hash: BytesLike,
      nodes: string[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidSignatures(
      hash: BytesLike,
      signatures: BytesLike[],
      signers: string[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyBlock(
      _hash: BytesLike,
      blockHeader: BytesLike,
      sigs: BytesLike[],
      merkleProofs: BytesLike[],
      position: BigNumberish,
      _appNode: string[],
      overrides?: CallOverrides
    ): Promise<[void]>;

    verifyEvent(
      _hash: BytesLike,
      _event: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;
  };

  c_0x94e56d13(
    c__0x94e56d13: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  isValidNodes(
    hash: BytesLike,
    nodes: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidSignatures(
    hash: BytesLike,
    signatures: BytesLike[],
    signers: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyBlock(
    _hash: BytesLike,
    blockHeader: BytesLike,
    sigs: BytesLike[],
    merkleProofs: BytesLike[],
    position: BigNumberish,
    _appNode: string[],
    overrides?: CallOverrides
  ): Promise<void>;

  verifyEvent(
    _hash: BytesLike,
    _event: BytesLike,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber]>;

  callStatic: {
    c_0x94e56d13(
      c__0x94e56d13: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    isValidNodes(
      hash: BytesLike,
      nodes: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidSignatures(
      hash: BytesLike,
      signatures: BytesLike[],
      signers: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyBlock(
      _hash: BytesLike,
      blockHeader: BytesLike,
      sigs: BytesLike[],
      merkleProofs: BytesLike[],
      position: BigNumberish,
      _appNode: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    verifyEvent(
      _hash: BytesLike,
      _event: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    c_0x94e56d13(
      c__0x94e56d13: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidNodes(
      hash: BytesLike,
      nodes: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidSignatures(
      hash: BytesLike,
      signatures: BytesLike[],
      signers: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyBlock(
      _hash: BytesLike,
      blockHeader: BytesLike,
      sigs: BytesLike[],
      merkleProofs: BytesLike[],
      position: BigNumberish,
      _appNode: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyEvent(
      _hash: BytesLike,
      _event: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0x94e56d13(
      c__0x94e56d13: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidNodes(
      hash: BytesLike,
      nodes: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignatures(
      hash: BytesLike,
      signatures: BytesLike[],
      signers: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyBlock(
      _hash: BytesLike,
      blockHeader: BytesLike,
      sigs: BytesLike[],
      merkleProofs: BytesLike[],
      position: BigNumberish,
      _appNode: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyEvent(
      _hash: BytesLike,
      _event: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
