POST {{baseURL}}/tx/{{blockchainRid}}
Content-Type: application/json

{
  "tx": ""
}

###

GET {{baseURL}}/tx/{{blockchainRid}}/{{txRid}}
Accept: application/json

###

GET {{baseURL}}/transactions/{{blockchainRid}}/{{txRid}}
Accept: application/json

###

GET {{baseURL}}/transactions/{{blockchainRid}}?limit={{limit}}&before-time={{beforeTime}}
Accept: application/json

###

GET {{baseURL}}/tx/{{blockchainRid}}/{{txRid}}/status
Accept: application/json

###

GET {{baseURL}}/blocks/{{blockchainRid}}?limit={{limit}}&before-time={{beforeTime}}&txs=true
Accept: application/json

###

GET {{baseURL}}/blocks/{{blockchainRid}}/{{blockRid}}?txs=true
Accept: application/json

###

POST {{baseURL}}/query/{{blockchainRid}}
Accept: application/json
Content-Type: application/json

{
  "type": "my_query",
  "arg1": 17,
  "arg2": "foo"
}

###

POST {{baseURL}}/batch_query/{{blockchainRid}}
Accept: application/json
Content-Type: application/json

{
  "queries": [
    {
      "type": "my_query",
      "arg1": 17,
      "arg2": "foo"
    },
    {
      "type": "other_query"
    }
  ]
}

###

GET {{baseURL}}/query/{{blockchainRid}}?type=my_query&arg1=17&arg2=foo
Accept: application/json

###

GET {{baseURL}}/dquery/{{blockchainRid}}?type=get_picture&id=4555
Accept: application/json

###

POST {{baseURL}}/query_gtx/{{blockchainRid}}
Accept: application/json
Content-Type: application/json

{
  "queries": [
    "A52E302CA20A0C086D795F7175657279A41E301C300B0C0461726731A303020111300D0C0461726732A2050C03666F6F",
    "A5153013A20D0C0B6F746865725F7175657279A4023000"
  ]
}

###
