POST {{baseURL}}/tx/{{blockchainRid}}
Content-Type: application/json

{"tx": ""}

###

GET {{baseURL}}/tx/{{blockchainRid}}/{{txRid}}
Accept: application/json

###

GET {{baseURL}}/transactions/{{blockchainRid}}/{{txRid}}
Accept: application/json

###

GET {{baseURL}}/transactions/{{blockchainRid}}?limit={{limit}}&before-time={{beforeTime}}
Accept: application/json

###

GET {{baseURL}}/tx/{{blockchainRid}}/{{txRid}}/status
Accept: application/json

###

GET {{baseURL}}/blocks/{{blockchainRid}}?limit={{limit}}&before-time={{beforeTime}}&txs=true
Accept: application/json

###

GET {{baseURL}}/blocks/{{blockchainRid}}/{{blockRid}}?txs=true
Accept: application/json

###
