GtxMessages DEFINITIONS ::= BEGIN

IMPORTS RawGtv FROM GtvMessages;

	GTXOperation ::= SEQUENCE {
		opName UTF8String,
		args SEQUENCE OF RawGtv
	}

	GTXBody ::= SEQUENCE {
		blockchainRID OCTET STRING,
		operations SEQUENCE OF GTXOperation,
		signers SEQUENCE OF OCTET STRING
	}
	
	GTXTransaction ::= SEQUENCE {
	    body SEQUENCE OF GTXBody,
		signatures SEQUENCE OF OCTET STRING
	}
	
END
