GtxMessages DEFINITIONS ::= BEGIN

IMPORTS RawGtv FROM GtvMessages;

	RawGtxOp ::= SEQUENCE {
		name UTF8String,
		args SEQUENCE OF RawGtv
	}

	RawGtxBody ::= SEQUENCE {
		blockchainRid OCTET STRING,
		operations SEQUENCE OF RawGtxOp,
		signers SEQUENCE OF OCTET STRING
	}
	
	RawGtx ::= SEQUENCE {
	    body RawGtxBody,
		signatures SEQUENCE OF OCTET STRING
	}
	
END
