GtxMessages DEFINITIONS ::= BEGIN

IMPORTS RawGtv FROM GtvMessages;

	GTXOperation ::= SEQUENCE {
		name UTF8String,
		args SEQUENCE OF RawGtv
	}

	GTXBody ::= SEQUENCE {
		blockchainRid OCTET STRING,
		operations SEQUENCE OF GTXOperation,
		signers SEQUENCE OF OCTET STRING
	}
	
	GTXTransaction ::= SEQUENCE {
	    body GTXBody,
		signatures SEQUENCE OF OCTET STRING
	}
	
END
