package net.postchain.gtv.merkle

import net.postchain.gtv.Gtv
import net.postchain.gtv.GtvArray
import net.postchain.gtv.GtvDictionary
import net.postchain.gtv.merkle.GtvMerkleBasics.HASH_PREFIX_NODE_GTV_ARRAY
import net.postchain.gtv.merkle.GtvMerkleBasics.HASH_PREFIX_NODE_GTV_DICT
import net.postchain.gtv.merkle.path.PathElement

/**
 * Two trees with the same leaves but different internal structure must hash differently, so arrays and
 * dictionaries get their own head-node types carrying distinct hash prefixes.
 */

/** Represents the top of a subtree generated by a [GtvArray] */
public class GtvArrayHeadNode(
    left: BinaryTreeElement,
    right: BinaryTreeElement,
    content: Gtv,
    public val size: Int,
    public val sizeInBytes: Int,
    pathElem: PathElement? = null,
) : SubTreeRootNode<Gtv>(left, right, content, pathElem) {

    init {
        if (content !is GtvArray) {
            throw IllegalStateException("How come we use this array type when the type is not an GtvArray?")
        }
    }

    override fun getPrefixByte(): Byte = HASH_PREFIX_NODE_GTV_ARRAY

    override fun getNrOfBytes(): Int = sizeInBytes
}

/** Represents the top of a subtree generated by a [GtvDictionary] */
public class GtvDictHeadNode(
    left: BinaryTreeElement,
    right: BinaryTreeElement,
    content: Gtv,
    public val size: Int,
    public val sizeInBytes: Int,
    pathElem: PathElement? = null,
) : SubTreeRootNode<Gtv>(left, right, content, pathElem) {

    init {
        if (content !is GtvDictionary) {
            throw IllegalStateException("How come we use this dict type when the type is not an GtvDictionary?")
        }
    }

    override fun getPrefixByte(): Byte = HASH_PREFIX_NODE_GTV_DICT

    override fun getNrOfBytes(): Int = sizeInBytes
}

/** Represents a [BinaryTree] that only holds Gtv values. */
public class GtvBinaryTree(root: BinaryTreeElement) : BinaryTree<Gtv>(root)
